version: "3.7"

services:
  plugin:
    build: .
    volumes:
      - ..:/workspace
      - ${M2_ROOT}/settings.xml:/usr/share/maven/conf/settings.xml:ro
      - m2:/m2:rw
    image: wada/datanucleus-devcontainer

volumes:
  m2:
